apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clock
  name: nginx-alpine-clock
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clock
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clock
    spec:
      containers:
        - image: viveksahu26/clock:latest
        imagePullPolicy: IfNotPresent
        name: nginx-alpine
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
