apiVersion: v1
kind: Service
metadata:
  labels:
    app: clock
  name: clock
  namespace: demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: clock
  type: NodePort
