apiVersion: v1
kind: Service
metadata:
  labels:
    app: clock
  name: nginx-alpine
  namespace: demo
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 8111
  selector:
    app: clock
  type: NodePort
